version: '3.8'
services:
  nginx:
    image: nginx:latest
    env_file:
      - ./test.env
    environment:
      - nenv=development
      - nstack=1
    configs:
      - source: te-conf
        target: /tmp
configs:
  te-conf:
    file: ./test.env
